server:
    type: default
    applicationConnectors:
        -   type: http
            port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: EST
      target: stdout
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %logger{36}%n%-5level [%thread] - %msg%n"

mail:
    username: swe4713brpeel@gmail.com
    password: spsu2015
    port: 587
    host: smtp.gmail.com
    notifyStart: false
    testMode: false

database:
  driverClass: org.postgresql.Driver

  # the username
  user: qzttshdkjehswf

  # the password
  password: gCaz38THpXvT3wOcJ7OoOsMGQy

  # the JDBC URL
  url: jdbc:postgresql://ec2-54-225-101-202.compute-1.amazonaws.com:5432/d2jlgecs85p9ca

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  #
  checkConnectionOnBorrow: true

  # how long a connection must be held before it can be validated
  maxConnectionAge: 10s

  # the maximum lifetime of an idle connection
  #closeConnectionIfIdleFor: 1 minute